export const COMPONENTS = 'index.js'
export const COMPONENTS_DIRECTORY = '.components'
export const MOULD_DIRECTORY = 'mould'
export const RESOLVERS = 'resolvers.ts'
export const SCHEMA = '.mould'
export const SYMLINK_MOULD_DIRECTORY = '.mould'
