'use strict'

const MOULD_DIRECTORY = 'mould'
const RESOLVERS = 'resolvers.ts'
const SYMLINK_MOULD_DIRECTORY = '.mould'

exports.MOULD_DIRECTORY = MOULD_DIRECTORY
exports.RESOLVERS = RESOLVERS
exports.SYMLINK_MOULD_DIRECTORY = SYMLINK_MOULD_DIRECTORY
